/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    'menu-items': MenuItem;
    'menu-categories': MenuCategory;
    media: Media;
    'form-submissions': FormSubmission;
    resumes: Resume;
    users: User;
    'payload-kv': PayloadKv;
    folders: FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    folders: {
      documentsAndFolders: 'folders' | 'media';
    };
  };
  collectionsSelect: {
    'menu-items': MenuItemsSelect<false> | MenuItemsSelect<true>;
    'menu-categories': MenuCategoriesSelect<false> | MenuCategoriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    resumes: ResumesSelect<false> | ResumesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    folders: FoldersSelect<false> | FoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    homepage: Homepage;
    'menu-page': MenuPage;
    'about-page': AboutPage;
    'contact-page': ContactPage;
    'site-settings': SiteSetting;
    'seo-defaults': SeoDefault;
  };
  globalsSelect: {
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    'menu-page': MenuPageSelect<false> | MenuPageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'contact-page': ContactPageSelect<false> | ContactPageSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'seo-defaults': SeoDefaultsSelect<false> | SeoDefaultsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Every drink and dish. Change the price here and the website updates on the next publish.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-items".
 */
export interface MenuItem {
  id: number;
  name: string;
  category: number | MenuCategory;
  /**
   * Ingredients or a short note, e.g. "cold foam served over iced espresso".
   */
  description?: string | null;
  /**
   * Numbers only, e.g. 5.5
   */
  price?: number | null;
  /**
   * Overrides the number, e.g. "+$0.75" or "market price".
   */
  priceLabel?: string | null;
  /**
   * e.g. Biscoff / Kinder Bueno / Nutella, or Small / Large with different prices.
   */
  variants?:
    | {
        name: string;
        price: number;
        id?: string | null;
      }[]
    | null;
  image?: (number | null) | Media;
  tags?:
    | (
        | 'New'
        | 'Popular'
        | 'Seasonal'
        | 'Vegan'
        | 'Gluten free'
        | 'Signature'
        | 'Rea Farms'
        | 'South End'
        | 'Lake Norman'
      )[]
    | null;
  featured?: boolean | null;
  available?: boolean | null;
  /**
   * Lower numbers show first.
   */
  order?: number | null;
  /**
   * Auto-generated from the name. Used for links like /menu#latte.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Top-level categories (Coffee, Matcha & more, Food and sweets…) and their sub-sections (Hot, Iced, Salty, Sweets). Set "Parent" to make a sub-section.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-categories".
 */
export interface MenuCategory {
  id: number;
  name: string;
  description?: string | null;
  /**
   * Leave empty for a top-level category. Pick "Coffee" to make this a section inside Coffee (e.g. Hot / Iced).
   */
  parent?: (number | null) | MenuCategory;
  image?: (number | null) | Media;
  /**
   * Lower numbers show first.
   */
  order?: number | null;
  active?: boolean | null;
  /**
   * Auto-generated from the name. Used for links like /menu#latte.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Photo library, organised in folders by page (Home · Menu · About · Gallery…). Upload into the right folder, add a short description, then pick the photo from the page or product.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the photo in one sentence, e.g. "Iced latte in a Babaloo cup on a stone table".
   */
  alt: string;
  caption?: string | null;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "folders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: number | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Messages sent from the Contact and Join our team forms.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: 'contact' | 'careers';
  status?: ('new' | 'replied' | 'archived') | null;
  summary?: string | null;
  email?: string | null;
  data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  resume?: (number | null) | Resume;
  meta?: {
    page?: string | null;
    userAgent?: string | null;
    ipHash?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Files attached to job applications. Open the message to see the applicant.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resumes".
 */
export interface Resume {
  id: number;
  applicant?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Super admins manage everything (including users). Editors edit content only.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role?: ('admin' | 'editor') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'menu-items';
        value: number | MenuItem;
      } | null)
    | ({
        relationTo: 'menu-categories';
        value: number | MenuCategory;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'resumes';
        value: number | Resume;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-items_select".
 */
export interface MenuItemsSelect<T extends boolean = true> {
  name?: T;
  category?: T;
  description?: T;
  price?: T;
  priceLabel?: T;
  variants?:
    | T
    | {
        name?: T;
        price?: T;
        id?: T;
      };
  image?: T;
  tags?: T;
  featured?: T;
  available?: T;
  order?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-categories_select".
 */
export interface MenuCategoriesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  parent?: T;
  image?: T;
  order?: T;
  active?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  status?: T;
  summary?: T;
  email?: T;
  data?: T;
  resume?: T;
  meta?:
    | T
    | {
        page?: T;
        userAgent?: T;
        ipHash?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resumes_select".
 */
export interface ResumesSelect<T extends boolean = true> {
  applicant?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "folders_select".
 */
export interface FoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Every section of the home page, in order. Drag to reorder; untick "Show this section" to hide one without deleting it.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  sections?:
    | (
        | {
            enabled?: boolean | null;
            slides?:
              | {
                  image: number | Media;
                  imageMobile?: (number | null) | Media;
                  title?: string | null;
                  subtitle?: string | null;
                  text?: string | null;
                  cta?: {
                    label?: string | null;
                    href?: string | null;
                    external?: boolean | null;
                  };
                  id?: string | null;
                }[]
              | null;
            interval?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            enabled?: boolean | null;
            speed?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'iconStrip';
          }
        | {
            enabled?: boolean | null;
            /**
             * The links themselves are managed by the super admin (Site settings → Navigation).
             */
            note?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'navRow';
          }
        | {
            enabled?: boolean | null;
            title?: string | null;
            /**
             * Each line break is kept, as in the design.
             */
            text: string;
            cta?: {
              label?: string | null;
              href?: string | null;
              external?: boolean | null;
            };
            /**
             * Lets links jump to this section, e.g. "locations" → /#locations.
             */
            anchor?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'intro';
          }
        | {
            enabled?: boolean | null;
            title?: string | null;
            text?: string | null;
            /**
             * The first one is used for Google (address, hours). Set "Coming soon" for future locations.
             */
            items?:
              | {
                  name: string;
                  scriptName?: string | null;
                  status: 'open' | 'coming-soon' | 'closed';
                  image?: (number | null) | Media;
                  address?: {
                    street?: string | null;
                    suite?: string | null;
                    city?: string | null;
                    region?: string | null;
                    postalCode?: string | null;
                    country?: string | null;
                  };
                  phone?: string | null;
                  email?: string | null;
                  hoursDisplay?:
                    | {
                        days: string;
                        hours: string;
                        id?: string | null;
                      }[]
                    | null;
                  hoursSpec?:
                    | {
                        dayOfWeek: (
                          'Monday' | 'Tuesday' | 'Wednesday' | 'Thursday' | 'Friday' | 'Saturday' | 'Sunday'
                        )[];
                        opens: string;
                        closes: string;
                        id?: string | null;
                      }[]
                    | null;
                  mapUrl?: string | null;
                  geo?: {
                    lat?: number | null;
                    lng?: number | null;
                  };
                  orderUrl?: string | null;
                  /**
                   * e.g. "Coming soon".
                   */
                  note?: string | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Lets links jump to this section, e.g. "locations" → /#locations.
             */
            anchor?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'locations';
          }
        | {
            enabled?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'clubStrip';
          }
        | {
            enabled?: boolean | null;
            title?: string | null;
            text?: string | null;
            limit?: number | null;
            cta?: {
              label?: string | null;
              href?: string | null;
              external?: boolean | null;
            };
            /**
             * Lets links jump to this section, e.g. "locations" → /#locations.
             */
            anchor?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featuredMenu';
          }
        | {
            enabled?: boolean | null;
            title?: string | null;
            images?:
              | {
                  image: number | Media;
                  caption?: string | null;
                  id?: string | null;
                }[]
              | null;
            limit?: number | null;
            /**
             * Lets links jump to this section, e.g. "locations" → /#locations.
             */
            anchor?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
        | {
            enabled?: boolean | null;
            title?: string | null;
            items?:
              | {
                  quote: string;
                  author: string;
                  role?: string | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Lets links jump to this section, e.g. "locations" → /#locations.
             */
            anchor?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
        | {
            enabled?: boolean | null;
            title: string;
            text?: string | null;
            cta?: {
              label?: string | null;
              href?: string | null;
              external?: boolean | null;
            };
            image?: (number | null) | Media;
            imageMobile?: (number | null) | Media;
            background?: ('cream' | 'concrete' | 'sage' | 'bark') | null;
            /**
             * Lets links jump to this section, e.g. "locations" → /#locations.
             */
            anchor?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            enabled?: boolean | null;
            title?: string | null;
            html: string;
            image?: (number | null) | Media;
            imageMobile?: (number | null) | Media;
            imagePosition?: ('left' | 'right') | null;
            background?: ('cream' | 'concrete' | 'sage') | null;
            /**
             * Lets links jump to this section, e.g. "locations" → /#locations.
             */
            anchor?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
      )[]
    | null;
  /**
   * Leave a field empty to use the site-wide default (Settings → SEO).
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    /**
     * Only if this page should point to another URL.
     */
    canonical?: string | null;
    ogTitle?: string | null;
    ogDescription?: string | null;
    ogImage?: (number | null) | Media;
    twitterCard?: ('summary_large_image' | 'summary') | null;
    robots?: ('index, follow' | 'noindex, follow') | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Intro text of the /menu page. The products and categories themselves are in the Menu group.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-page".
 */
export interface MenuPage {
  id: number;
  intro?: {
    title?: string | null;
    text?: string | null;
  };
  showPrices?: boolean | null;
  /**
   * Leave a field empty to use the site-wide default (Settings → SEO).
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    /**
     * Only if this page should point to another URL.
     */
    canonical?: string | null;
    ogTitle?: string | null;
    ogDescription?: string | null;
    ogImage?: (number | null) | Media;
    twitterCard?: ('summary_large_image' | 'summary') | null;
    robots?: ('index, follow' | 'noindex, follow') | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Sections of /about, top to bottom.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  title?: string | null;
  frames?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Line breaks are kept.
   */
  text: string;
  showTeamSection?: boolean | null;
  teamImage?: (number | null) | Media;
  join?: {
    title?: string | null;
    text?: string | null;
    positions?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
    experienceLevels?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  showContactSection?: boolean | null;
  /**
   * Leave a field empty to use the site-wide default (Settings → SEO).
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    /**
     * Only if this page should point to another URL.
     */
    canonical?: string | null;
    ogTitle?: string | null;
    ogDescription?: string | null;
    ogImage?: (number | null) | Media;
    twitterCard?: ('summary_large_image' | 'summary') | null;
    robots?: ('index, follow' | 'noindex, follow') | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Everything on /contact: the form texts on the left and the contact details on the right.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page".
 */
export interface ContactPage {
  id: number;
  title?: string | null;
  text?: string | null;
  /**
   * Leave a field empty to hide it.
   */
  details?: {
    email?: string | null;
    phone?: string | null;
    locationName?: string | null;
    address?: string | null;
    hours?:
      | {
          days: string;
          hours: string;
          id?: string | null;
        }[]
      | null;
    mapUrl?: string | null;
    mapLabel?: string | null;
    showSocial?: boolean | null;
  };
  /**
   * Leave a field empty to use the site-wide default (Settings → SEO).
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    /**
     * Only if this page should point to another URL.
     */
    canonical?: string | null;
    ogTitle?: string | null;
    ogDescription?: string | null;
    ogImage?: (number | null) | Media;
    twitterCard?: ('summary_large_image' | 'summary') | null;
    robots?: ('index, follow' | 'noindex, follow') | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Business name, contact details, social links and navigation. Used on every page and for Google.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  name: string;
  legalName?: string | null;
  tagline?: string | null;
  logo?: (number | null) | Media;
  priceRange?: ('$' | '$$' | '$$$') | null;
  copyright?: string | null;
  phone?: string | null;
  email?: string | null;
  address?: {
    street?: string | null;
    suite?: string | null;
    city?: string | null;
    region?: string | null;
    postalCode?: string | null;
    country?: string | null;
  };
  mapUrl?: string | null;
  orderUrl?: string | null;
  social?:
    | {
        platform: 'instagram' | 'facebook' | 'tiktok' | 'x' | 'youtube' | 'whatsapp' | 'other';
        label?: string | null;
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Use "/#locations" to scroll to the locations on the home page.
   */
  nav?:
    | {
        label?: string | null;
        href?: string | null;
        external?: boolean | null;
        id?: string | null;
      }[]
    | null;
  footerNav?:
    | {
        label?: string | null;
        href?: string | null;
        external?: boolean | null;
        id?: string | null;
      }[]
    | null;
  primaryCta?: {
    label?: string | null;
    href?: string | null;
    external?: boolean | null;
  };
  secondaryCta?: {
    label?: string | null;
    href?: string | null;
    external?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Site-wide defaults. Each page can override them in its own SEO box (super admin only).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-defaults".
 */
export interface SeoDefault {
  id: number;
  /**
   * %s is replaced by the page title.
   */
  titleTemplate?: string | null;
  defaultTitle?: string | null;
  description?: string | null;
  ogImage?: (number | null) | Media;
  twitterHandle?: string | null;
  robots?: string | null;
  locale?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  sections?:
    | T
    | {
        hero?:
          | T
          | {
              enabled?: T;
              slides?:
                | T
                | {
                    image?: T;
                    imageMobile?: T;
                    title?: T;
                    subtitle?: T;
                    text?: T;
                    cta?:
                      | T
                      | {
                          label?: T;
                          href?: T;
                          external?: T;
                        };
                    id?: T;
                  };
              interval?: T;
              id?: T;
              blockName?: T;
            };
        iconStrip?:
          | T
          | {
              enabled?: T;
              speed?: T;
              id?: T;
              blockName?: T;
            };
        navRow?:
          | T
          | {
              enabled?: T;
              note?: T;
              id?: T;
              blockName?: T;
            };
        intro?:
          | T
          | {
              enabled?: T;
              title?: T;
              text?: T;
              cta?:
                | T
                | {
                    label?: T;
                    href?: T;
                    external?: T;
                  };
              anchor?: T;
              id?: T;
              blockName?: T;
            };
        locations?:
          | T
          | {
              enabled?: T;
              title?: T;
              text?: T;
              items?:
                | T
                | {
                    name?: T;
                    scriptName?: T;
                    status?: T;
                    image?: T;
                    address?:
                      | T
                      | {
                          street?: T;
                          suite?: T;
                          city?: T;
                          region?: T;
                          postalCode?: T;
                          country?: T;
                        };
                    phone?: T;
                    email?: T;
                    hoursDisplay?:
                      | T
                      | {
                          days?: T;
                          hours?: T;
                          id?: T;
                        };
                    hoursSpec?:
                      | T
                      | {
                          dayOfWeek?: T;
                          opens?: T;
                          closes?: T;
                          id?: T;
                        };
                    mapUrl?: T;
                    geo?:
                      | T
                      | {
                          lat?: T;
                          lng?: T;
                        };
                    orderUrl?: T;
                    note?: T;
                    id?: T;
                  };
              anchor?: T;
              id?: T;
              blockName?: T;
            };
        clubStrip?:
          | T
          | {
              enabled?: T;
              id?: T;
              blockName?: T;
            };
        featuredMenu?:
          | T
          | {
              enabled?: T;
              title?: T;
              text?: T;
              limit?: T;
              cta?:
                | T
                | {
                    label?: T;
                    href?: T;
                    external?: T;
                  };
              anchor?: T;
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              enabled?: T;
              title?: T;
              images?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    id?: T;
                  };
              limit?: T;
              anchor?: T;
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              enabled?: T;
              title?: T;
              items?:
                | T
                | {
                    quote?: T;
                    author?: T;
                    role?: T;
                    id?: T;
                  };
              anchor?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              enabled?: T;
              title?: T;
              text?: T;
              cta?:
                | T
                | {
                    label?: T;
                    href?: T;
                    external?: T;
                  };
              image?: T;
              imageMobile?: T;
              background?: T;
              anchor?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              enabled?: T;
              title?: T;
              html?: T;
              image?: T;
              imageMobile?: T;
              imagePosition?: T;
              background?: T;
              anchor?: T;
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        canonical?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        twitterCard?: T;
        robots?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-page_select".
 */
export interface MenuPageSelect<T extends boolean = true> {
  intro?:
    | T
    | {
        title?: T;
        text?: T;
      };
  showPrices?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        canonical?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        twitterCard?: T;
        robots?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  title?: T;
  frames?:
    | T
    | {
        image?: T;
        id?: T;
      };
  text?: T;
  showTeamSection?: T;
  teamImage?: T;
  join?:
    | T
    | {
        title?: T;
        text?: T;
        positions?:
          | T
          | {
              label?: T;
              id?: T;
            };
        experienceLevels?:
          | T
          | {
              label?: T;
              id?: T;
            };
      };
  showContactSection?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        canonical?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        twitterCard?: T;
        robots?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  title?: T;
  text?: T;
  details?:
    | T
    | {
        email?: T;
        phone?: T;
        locationName?: T;
        address?: T;
        hours?:
          | T
          | {
              days?: T;
              hours?: T;
              id?: T;
            };
        mapUrl?: T;
        mapLabel?: T;
        showSocial?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        canonical?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        twitterCard?: T;
        robots?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  name?: T;
  legalName?: T;
  tagline?: T;
  logo?: T;
  priceRange?: T;
  copyright?: T;
  phone?: T;
  email?: T;
  address?:
    | T
    | {
        street?: T;
        suite?: T;
        city?: T;
        region?: T;
        postalCode?: T;
        country?: T;
      };
  mapUrl?: T;
  orderUrl?: T;
  social?:
    | T
    | {
        platform?: T;
        label?: T;
        url?: T;
        id?: T;
      };
  nav?:
    | T
    | {
        label?: T;
        href?: T;
        external?: T;
        id?: T;
      };
  footerNav?:
    | T
    | {
        label?: T;
        href?: T;
        external?: T;
        id?: T;
      };
  primaryCta?:
    | T
    | {
        label?: T;
        href?: T;
        external?: T;
      };
  secondaryCta?:
    | T
    | {
        label?: T;
        href?: T;
        external?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-defaults_select".
 */
export interface SeoDefaultsSelect<T extends boolean = true> {
  titleTemplate?: T;
  defaultTitle?: T;
  description?: T;
  ogImage?: T;
  twitterHandle?: T;
  robots?: T;
  locale?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}